logging:
  level:
    org.apache.coyote.http11: debug

file:
  dir: /Users/hakhyeonsong/study/filetest/
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
